backend:
  name: git-gateway
branch: main
media_folder: "public/assets"
public_folder: "/assets"
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tag", name: "tags", widget: "list", default: ["post"] }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Image Caption", name: "imageCaption", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
  - name: "circular"
    label: "Circular"
    folder: "src/circular"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Destination", name: "destination", widget: "string" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Tag", name: "tags", widget: "list", default: ["circular"] }
      - { label: "Reference No", name: "referenceNo", widget: "string" }
      - { label: "Content", name: "content", widget: "markdown" }
      - { label: "Signature", name: "signature", widget: "string" }
      - { label: "Rank", name: "rank", widget: "string" }
      - { label: "CC", name: "cc", widget: "list" }
